### ISSUE TITLE
result

### ISSUE THREAD

**Issue by holgerBerger** [travisdowns/avx-turbo#3]
[output.txt](https://github.com/travisdowns/avx-turbo/files/2319163/output.txt)

no error report, just some result.
from dual socket
Model name:            Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz

**Comment by travisdowns** [comment]
Thanks! I will [include the model name](https://github.com/travisdowns/avx-turbo/issues/4) in the output in the future.

The AVX2 and AVX-512 turbo ration look lower than documented for the 6130. Intel claims 3.7/3.6/3.5 GHz for the Gold 6130 (1 thread), but this test shows 3.7/3.5/3.3. This could occur if two other cores are active during the test (because 1 and 2 cores have the same ratios), but the results are fairly stable, so the other thing would have to be running 100% of the time. Also, the non-AVX turbo ratio shows up as 3.7 as advertised, indicating that there are only 1 or 2 cores active.

Just curious, are you using intel_pstate? You can check `cpupower frequency-info`.

Here's the chart I used to [look up the expected ratios](https://www.anandtech.com/show/11544/intel-skylake-ep-vs-amd-epyc-7000-cpu-battle-of-the-decade/8).

**Comment by travisdowns** [comment]
Closing this so it doesn't show as an open issue to fix, but of course it's still open for comments.

**Comment by travisdowns** [comment]
@holgerBerger - if you get a chance, I'd be interested in another run with `--iters 1000000`.

**Comment by holgerBerger** [comment]
will upload soon, will run on two different samples.

acpi is used, not intel_pstate.

**Comment by holgerBerger** [comment]
[output8160.txt](https://github.com/travisdowns/avx-turbo/files/2320889/output8160.txt)

this is a sample from a Platinum 8160

numactl --cpunodebind=0 ./avx-turbo --max-threads=24 --iters 1000000

**Comment by holgerBerger** [comment]
[output7501.txt](https://github.com/travisdowns/avx-turbo/files/2320907/output7501.txt)

AMD EPYC 7501

numactl --cpunodebind=0 ./avx-turbo --max-threads=32

**Comment by holgerBerger** [comment]
I submitted a few more results there, but can not see it anymore...

2018-08-25 0:33 GMT+02:00 travisdowns <notifications@github.com>:

**Comment by travisdowns** [comment]
Thanks @holgerBerger !

If you have a chance, I'm wondering if you could do another run for me. It could be on the gold or the platinum.

I've added a mode where you can do a test which is a mix of code, versus the existing tests which run on the same code on every core. That's the test I'm interested in.

You could run this:

    for i in {0..10}; do f=$((10-i)); echo "Scalar $i, fma $f"; sudo ./avx-turbo --spec scalar_iadd/$i,avx256_fma_t/$f; done

Just on one socket. Replace `10` the two places it occurs with the number of cores on the socket. Ideally, hyperthreading off (or HT cores offlined).

It would help a lot to diagnose the frequency behavior of Intel CPUs with mixed loads: something that is currently not documented anywhere.

**Comment by holgerBerger** [comment]
Am Mi., 5. Sep. 2018 um 06:00 Uhr schrieb travisdowns <
notifications@github.com>:
